name: SILShack Summer 2018

title: SILShack

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/New_York

# You betcha
gems:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - assignments
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

baseurl: /summer2018
url: /summer2018

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Summer 2018

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: http://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "#"
    github: tommytester
    twitter:
    about: "Testin' INLS 560 since 2014"

  draravindrk:
    name: draravindrk
    prof: false
    gravatar:
    website: "#"
    github: draravindrk
    twitter:
    about: "Here's a little about draravindrk"

  hollaATyacodegirl:
    name: hollaATyacodegirl
    prof: false
    gravatar:
    website: "#"
    github: hollaATyacodegirl
    twitter:
    about: "Here's a little about hollaATyacodegirl"

  kevin-kao:
    name: kevin-kao
    prof: false
    gravatar:
    website: "#"
    github: kevin-kao
    twitter:
    about: "Here's a little about kevin-kao"

  NobrineCalc:
    name: NobrineCalc
    prof: false
    gravatar:
    website: "#"
    github: NobrineCalc
    twitter:
    about: "Here's a little about NobrineCalc"

  ponderm:
    name: ponderm
    prof: false
    gravatar:
    website: "#"
    github: ponderm
    twitter:
    about: "Here's a little about ponderm"

  rachelanniexo:
    name: rachelanniexo
    prof: false
    gravatar:
    website: "#"
    github: rachelanniexo
    twitter:
    about: "Here's a little about rachelanniexo"

  scylarmartin:
    name: scylarmartin
    prof: false
    gravatar:
    website: "#"
    github: scylarmartin
    twitter:
    about: "Here's a little about scylarmartin"

  TCarmon:
    name: TCarmon
    prof: false
    gravatar:
    website: "#"
    github: TCarmon
    twitter:
    about: "Here's a little about TCarmon"

